const dogsdata = {
  dogCollection: [
    {
      _id: "dog1",
      name: "Buddy",
      breed: "Labrador Retriever",
      bio: "Friendly and playful",
      tags: ["friendly", "playful"],
      lookingForPartner: true,
      picture: "Pup1.jpg",
    },
    {
      _id: "dog2",
      name: "Max",
      breed: "Golden Retriever",
      bio: "Loves to swim and fetch",
      tags: ["active", "friendly"],
      lookingForPartner: true,
      picture: "Pup2.jpg",
    },
    {
      _id: "dog3",
      name: "Lucy",
      breed: "Poodle",
      bio: "Smart and affectionate",
      tags: ["intelligent", "cute"],
      lookingForPartner: true,
      picture: "Pup3.jpg",
    },
    {
      _id: "dog4",
      name: "Lucy",
      breed: "Dachshund",
      bio: "Smart and affectionate",
      tags: ["intelligent", "cute", "funny"],
      lookingForPartner: true,
      picture: "pup4.jpg",
    },
    {
      _id: "dog5",
      name: "Jack",
      breed: "Denmark Feist",
      bio: "Smart and affectionate",
      tags: ["cute"],
      lookingForPartner: true,
      picture: "Pup5.jpg",
    },
    {
      _id: "dog6",
      name: "Lucky",
      breed: "Akita",
      bio: "Adorable and cuddly",

      tags: ["intelligent", "cute"],
      lookingForPartner: true,
      picture: "Pup6.jpg",
    },
    {
      _id: "dog7",
      name: "Momo",
      breed: "Alaskan Malamute",
      bio: "Smart and affectionate",
      tags: ["intelligent", "cute"],
      lookingForPartner: true,
      picture: "Pup7.jpg",
    },
    {
      _id: "dog8",
      name: "Coco",
      breed: "Denmark Feist",
      bio: "Easygoing and friendly",
      tags: ["easygoing", "friendly"],
      lookingForPartner: true,
      picture: "Pup8.jpg",
    },
    {
      _id: "dog9",
      name: "Lucy",
      breed: "American Cocker Spaniel",
      bio: "Protective and loyal",
      tags: ["loyal", "protective"],

      lookingForPartner: true,
      picture: "Pup9.jpg",
    },
    {
      _id: "dog10",
      name: "Fofo",
      breed: "Denmark Feist",
      bio: "Loves to swim and fetch",
      tags: ["active", "friendly"],
      lookingForPartner: true,
      picture: "Pup10.jpg",
    },
    {
      _id: "dog11",
      name: "Yucki",
      breed: "Bulldog",
      bio: "Friendly and playful",
      tags: ["friendly", "playful"],
      lookingForPartner: true,
      picture: "Pup11.jpg",
    },
    {
      _id: "dog12",
      name: "Faisel",
      breed: "Beagle",
      bio: " affectionate",
      tags: ["intelligent", "cute"],
      lookingForPartner: true,
      picture: "Pup12.jpg",
    },
    {
      _id: "dog13",
      name: "Mosh",
      breed: "Denmark Feist",
      bio: "Easygoing and friendly",
      tags: ["easygoing", "friendly"],
      lookingForPartner: true,
      picture: "Pup13.jpg",
    },
    {
      _id: "dog14",
      name: "Daisy",
      breed: "Denmark Feist",
      bio: "Smart and affectionate",
      tags: ["intelligent"],
      lookingForPartner: true,
      picture: "Pup14.jpg",
    },
    {
      _id: "dog15",
      name: "Lucy",
      breed: "German Shepherd",
      bio: "Smart and affectionate",
      tags: ["intelligent", "cute"],
      lookingForPartner: true,
      picture: "Pup15.jpg",
    },


  ],
};

module.exports = dogsdata;
